// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfhrPyTU8ZaQBSPv3OFjWRckh9J0gENxk',
    appId: '1:101590734342:web:dc65edc5315e4aa9361587',
    messagingSenderId: '101590734342',
    projectId: 'udemy-flutter-ed254',
    authDomain: 'udemy-flutter-ed254.firebaseapp.com',
    storageBucket: 'udemy-flutter-ed254.appspot.com',
    measurementId: 'G-Q9V9C7ELXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-w2wkLRP9gcDecPJTf951zV5r7JsgsDE',
    appId: '1:101590734342:android:965531d3abc6a95f361587',
    messagingSenderId: '101590734342',
    projectId: 'udemy-flutter-ed254',
    storageBucket: 'udemy-flutter-ed254.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyLVtkxTHJ8ujKSCuCrpDqmQ4SJkExt2Y',
    appId: '1:101590734342:ios:d8ed016368bcc944361587',
    messagingSenderId: '101590734342',
    projectId: 'udemy-flutter-ed254',
    storageBucket: 'udemy-flutter-ed254.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyLVtkxTHJ8ujKSCuCrpDqmQ4SJkExt2Y',
    appId: '1:101590734342:ios:d8ed016368bcc944361587',
    messagingSenderId: '101590734342',
    projectId: 'udemy-flutter-ed254',
    storageBucket: 'udemy-flutter-ed254.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfhrPyTU8ZaQBSPv3OFjWRckh9J0gENxk',
    appId: '1:101590734342:web:0739d33f1d3ff0ba361587',
    messagingSenderId: '101590734342',
    projectId: 'udemy-flutter-ed254',
    authDomain: 'udemy-flutter-ed254.firebaseapp.com',
    storageBucket: 'udemy-flutter-ed254.appspot.com',
    measurementId: 'G-NEFS1YN2MV',
  );
}
